# Generated by Django 4.2.3 on 2023-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lname",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
    ]
